# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41eda1c1b25424ab853d51a06f507670105629fbe5a72a4b546e52a92667a085e58172939c783f93a96fcf02943ecbcded5cdc48ab424e92fa755e6ab3f98b49

test:
  secret_key_base: b10d33d280d1679ff1fe64c958dbc4a8bcf24e9b0030c1182386be9252a3f61f3d2fc1b8af5d40cf75c5c1ca9e398a6200989c44902df1785af95f27cccc8f68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
